title: iotize
description: just trying to get something to build in Xcode
theme: minima
baseurl: /
domain_name: 'http://iotize.github.com'
twitter_username: iotize
github_username:  iotize
rss: rss

# Details for the RSS feed generator
url:            'http://iotize.github.com'
author:         'Ryan Davies'
authorTwitter:  'iotize'

permalink:       /:year/:title/
