title: iotize
description: iOS Engineer
theme: minima
markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'http://iotize.github.com'
twitter_username: iotize
github_username:  iotize
rss: rss

# Details for the RSS feed generator
url:            'http://iotize.github.com'
author:         'iotize'
authorTwitter:  'iotize'

permalink:       /:year/:title/
