name: Ryan Davies - 📱 Engineer
description: iOS Engineer @ notonthehighstreet.com
meta_description: "Ryan Davies, iOS Engineer at notonthehighstreet.com. Blogging about iOS, Mac, and tvOS development – all things Swift and Objective-C."

aboutPage: true

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'http://ryanjdavies.com'
google_analytics: 'UA-57241786-2'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://ryanjdavies.com'
author:         'Ryan Davies'
authorTwitter:  'iotize'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
