name: iotize, 📱 engineer
description: iOS Engineer
meta_description: ""
markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'http://iotize.github.com'

# Details for the RSS feed generator
url:            'http://iotize.github.com'
author:         'Ryan Davies'
authorTwitter:  'iotize'

permalink:       /:year/:title/

theme: jekyll-theme-midnight