# Permalinks
permalink:           pretty

# Setup
title:               Ryan Davies
tagline:             iOS & web developer from the sunny UK.
url:                 http://ryanjdavies.com
paginate:            1
baseurl:             ""
pages_list:       
  About:   '/about'
  Archive: '/archive'
  Feed:    '/atom.xml'

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ryan Davies
  url:               https://twitter.com/iotize
  email:             mail@ryanjdavies.com

# Custom vars
github:				 https://github.com/iotize

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
