name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    if: "!contains(format('{0} {1} {2}', github.event.head_commit.message, github.event.pull_request.title, github.event.pull_request.body), '[skip ci]')"
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Generate
      run: swift run -v Publisher
    - name: List
      run: ls -lR
